Description: >
  UdaPeople backend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String
 # KeyName:
 #   Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS instances
 #   Type: AWS::EC2::KeyPair::KeyName
 #   Default: udapeople

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub UdaPeople-${ID}
      GroupDescription: Allow port 22 and port 3030.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udapeople  
    #  KeyName: !Ref KeyName # If you use another key pair name, you should change this value to match.
      ImageId: ami-0892d3c7ee96c0bf7 
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}
